version: "3.9"
services:
  strapi:
    build: ./docker-example-strapi
    ports:
      - "1337:1337"
    depends_on:
      - "db"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: strapi
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_PORT: 5432
    volumes:
      - ./docker-example-strapi:/app
      - /app/node_modules
  frontend:
    build: ./docker-example-ecom
    ports:
      - "3000:3000"
    volumes:
      - ./docker-example-ecom:/app
      - /app/node_modules
  db:
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: strapi
    volumes:
      - example-pgdata:/var/lib/postgresql/data
volumes:
  example-pgdata:
    external: true
